Feature/import wyw0
sbgisen/dynamic_slam_tool pull request #1
Opened 2023-01-16 14:16 UTC by nyxrobotics

## Summary
- Import files from [WYW0](https://github.com/WYW0)/[Dynamic-object-detection-for-unstructured-road](https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road)

2023-01-17 05:52 UTC, Tacha-S requested changes
reformatがPRに混ざってるせいでどこまでがwyw0の成果でどう統合したのかwyw0のrepoじゃだめだったのか全然わかりません

2023-01-17 08:30 UTC, nyxrobotics commented
> reformatがPRに混ざってるせいでどこまでがwyw0の成果でどう統合したのかwyw0のrepoじゃだめだったのか全然わかりません

説明のためissue立てました #3 
wywoはファイルを本家からコピーして最新版を上書きしたようなコミットになっています。
https://github.com/WYW0/Dynamic-object-detection-for-unstructured-road/commits/main
本家を本流にして必要な変更のみ取り込もうとした結果が本PRです。
Revierwe目線で「何が取り込まれたかわからない」状態であればどのみちwyw0と同じ状況なので、wyw0をfork元にしたほうが良いという判断もできます。

2023-01-17 09:29 UTC, Tacha-S requested changes

2023-01-17 09:29 UTC, Tacha-S commented on src/MovingObjectRemoval.cpp
>    //cb->groundPlaneRemoval(trim_x,trim_y); //groud plane removal (voxel covariance)
論文通りかという基準で行くとRANSACが一般的でvoxel covarianceのほうが適してるって話のようですが、cropBoxしかしてない地面検出?ただの範囲抽出をしているのはこれでいいんですか？

2023-01-17 09:35 UTC, nyxrobotics commented on src/MovingObjectRemoval.cpp
>    //cb->groundPlaneRemoval(trim_x,trim_y); //groud plane removal (voxel covariance)
trim_x, trim_y, trim_zは（おそらく計算能力が低いシステム向けに）検出範囲を箱型で絞っているだけのようです。
地面の除去に当たる部分はgp_limitのパラメータで指定していて、LiDARから見た地面の高さを代入するようになっています。
パラメータの説明はVariableDescription.txtに書かれています。

2023-01-17 09:45 UTC, Tacha-S commented on src/MovingObjectRemoval.cpp
>    //cb->groundPlaneRemoval(trim_x,trim_y); //groud plane removal (voxel covariance)
論文とは手法が異なりますが...
Fig. 1だけ信じてそれっぽいことしていればいいということですか？

2023-01-17 10:06 UTC, nyxrobotics commented on src/MovingObjectRemoval.cpp
>    //cb->groundPlaneRemoval(trim_x,trim_y); //groud plane removal (voxel covariance)
失礼しました、voxel covarianceに当たる処理はgp_leafを使っている部分のようです。
gp_limitは論文に該当箇所見つからなかったためスルーしていただいて良いです。

2023-01-18 09:34 UTC, Tacha-S commented on src/MovingObjectRemoval.cpp
>    //cb->groundPlaneRemoval(trim_x,trim_y); //groud plane removal (voxel covariance)
https://github.com/sbgisen/dynamic_slam_tool/issues/3#issuecomment-1385055407

> レビューしてほしかったものにこのあたりのことを含むで今の流れであっています。

これの解釈が間違っているのかもしれませんが全く論文の手法に沿ってないのにスルーとはとなっているんですが。

論文で述べている手法に合わせたからレビューしてほしいではなくて、この動かないソースコードを論文との齟齬は抜きにしてそれらしく動かしているものがあったのでそれを流用し、config周りのみを修正したから動くかどうか見てほしいということでいいですか？

2023-01-18 10:58 UTC, nyxrobotics commented
理解しました。MovingObjectDetectionCloud::groundPlaneRemovalについて
下記2種類が実装されており、後者はコメントアウトされているので書き換えないと動作確認できませんでした。
取り急ぎ共有します。（確認しておきます。）

- ```void MovingObjectDetectionCloud::groundPlaneRemoval(float x,float y,float z)``` : 高さの定数値で地面を削除する方法
https://github.com/sbgisen/dynamic_slam_tool/blob/ea925e0f0f8b8a01a871de55b243620bb1261ebe/src/MovingObjectRemoval.cpp#L62-L64

- ```void MovingObjectDetectionCloud::groundPlaneRemoval(float x,float y)``` : voxel covarianceを使用して地面を削除する方法
https://github.com/sbgisen/dynamic_slam_tool/blob/ea925e0f0f8b8a01a871de55b243620bb1261ebe/src/MovingObjectRemoval.cpp#L90-L93

- 変更が必要な箇所
https://github.com/sbgisen/dynamic_slam_tool/blob/ea925e0f0f8b8a01a871de55b243620bb1261ebe/src/MovingObjectRemoval.cpp#L526-L527

2023-01-19 02:38 UTC, nyxrobotics commented on src/MovingObjectRemoval.cpp
>    //cb->groundPlaneRemoval(trim_x,trim_y); //groud plane removal (voxel covariance)
修正をするのに必要な作業が想定より多かったため別でissue立てました。
このPRでは動くかどうかのみ確認をお願いします。

2023-01-19 05:20 UTC, Tacha-S commented
黒点がもともとのvelodyneの点群で、intensityで色がついているのがこのノードの出力ですが、近距離でフィルターされていそうですが、用途的にいいんですか？
![Screenshot from 2023-01-19 14-12-20](https://user-images.githubusercontent.com/13605820/213360718-d6ab2f3a-eace-4c9f-88a0-01519c51bf34.png)

市役所から出ていく直線脇の低木？草？が全部消えます。
![Screenshot from 2023-01-19 14-16-23](https://user-images.githubusercontent.com/13605820/213361190-a09d413c-02fa-4e44-b4a8-5211c4331790.png)

マーカーの消し忘れなのかわからないがBoundingBox出ているのに点群が残っているときがある。
![Screenshot from 2023-01-19 14-18-46](https://user-images.githubusercontent.com/13605820/213361524-cccf699d-b258-4801-b3d9-cab8d1f70099.png)

このパッケージがこの程度の性能って言う事ならこのままなんか動きはしているのでいいと思います。

2023-02-06 06:26 UTC, jsupratman13 requested changes
遅れも手申し訳けございません．

動作確認は取れましたが，どうしますか？使いやすいや性能評価は別としてこのままマージしますか？

2023-02-06 06:26 UTC, jsupratman13 commented on CMakeLists.txt
>    message_filters
自分の環境だとこのままビルドできなかったので以下を修正したらビルドできました．

```
add_definitions(-std=c++17)
```

2023-02-06 06:33 UTC, Tacha-S commented on CMakeLists.txt
>    message_filters
wheeltecの動作環境がmelodicなので`add_definitions(-std=c++17)`はいらないと思います。
マージはおまかせします

2023-02-06 06:33 UTC, nyxrobotics commented on CMakeLists.txt
>    message_filters
コンパイラによってc++0xかc++11かが異なるようです。エラーの内容など知りたいので別途issue立ててもらえると嬉しいです。
https://github.com/sbgisen/dynamic_slam_tool/blob/ea925e0f0f8b8a01a871de55b243620bb1261ebe/CMakeLists.txt#L3

2023-02-06 06:33 UTC, nyxrobotics commented
> 遅れて申し訳けございません．
> 
> 動作確認は取れましたが，どうしますか？使いやすいや性能評価は別としてこのままマージしますか？

お願いします

2023-02-06 07:14 UTC, jsupratman13 commented on CMakeLists.txt
>    message_filters
なるほど了解いたしました。

2023-02-06 07:14 UTC, merged